// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtV_g-nRX2ZC211uzIRIRfnf-XpHEjixk',
    appId: '1:872555342647:web:8f5caac9674a46475408b2',
    messagingSenderId: '872555342647',
    projectId: 'fund2me-21bb8',
    authDomain: 'fund2me-21bb8.firebaseapp.com',
    storageBucket: 'fund2me-21bb8.appspot.com',
    measurementId: 'G-90WMCTS504',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSgBScUSzgySZ4eLCkFxjf6_ZGIgXMOfY',
    appId: '1:872555342647:android:2f4158aeb09406a05408b2',
    messagingSenderId: '872555342647',
    projectId: 'fund2me-21bb8',
    storageBucket: 'fund2me-21bb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxiwaiFPHSKoevbrLtq1puT-bVagSO1i8',
    appId: '1:872555342647:ios:d44b7d7e60a8353d5408b2',
    messagingSenderId: '872555342647',
    projectId: 'fund2me-21bb8',
    storageBucket: 'fund2me-21bb8.appspot.com',
    iosBundleId: 'com.example.fund2me1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxiwaiFPHSKoevbrLtq1puT-bVagSO1i8',
    appId: '1:872555342647:ios:d44b7d7e60a8353d5408b2',
    messagingSenderId: '872555342647',
    projectId: 'fund2me-21bb8',
    storageBucket: 'fund2me-21bb8.appspot.com',
    iosBundleId: 'com.example.fund2me1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtV_g-nRX2ZC211uzIRIRfnf-XpHEjixk',
    appId: '1:872555342647:web:1b6734548081d4565408b2',
    messagingSenderId: '872555342647',
    projectId: 'fund2me-21bb8',
    authDomain: 'fund2me-21bb8.firebaseapp.com',
    storageBucket: 'fund2me-21bb8.appspot.com',
    measurementId: 'G-KZ6P5WELHT',
  );
}
